os: osx
language: objective-c
osx_image: xcode9.2
env:
  - PLAT=macOS    DST="arch=x86_64"
  - PLAT=iOS      DST="OS=11.2,name=iPhone SE"
  - PLAT=tvOS     DST="OS=11.2,name=Apple TV"
  - PLAT=watchOS  DST="OS=4.2,name=Apple Watch - 38mm"
cache:
  directories:
  - Carthage
install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLAT
script:
  - set -o pipefail
  - xcodebuild -scheme PMKBolts -quiet -destination "$DST" build
  - if [ "$PLAT" != "watchOS" ]; then
      xcodebuild -scheme PMKBolts -quiet -destination "$DST" test;
    fi
